In [5]:
import numpy as np

In [17]:
arr = np.array([1, 2, 3, 4, 5])
result = []


In [18]:
for x in arr:
    result.append(x**2)

In [19]:
result

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]

In [20]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 
result

array([ 1,  4,  9, 16, 25])

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

x = arr2 - arr1
x

array([ 9, 18, 27])

In [28]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

mean = data.mean(axis=0)
std = data.std(axis=0)
normalized_data = (data - mean) / std
normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])