In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,])
arr

array([1, 2, 3, 4])

In [7]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full((3,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(0,100,6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [26]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [28]:
myarr = np.array([[10,76,15],[34,86,43],[85,63,42],[99,34,21]])

In [29]:
myarr

array([[10, 76, 15],
       [34, 86, 43],
       [85, 63, 42],
       [99, 34, 21]])

In [31]:
myarr.shape

(4, 3)

In [32]:
myarr.size

12

In [33]:
myarr.ndim

2

In [35]:
myarr.dtype

dtype('int64')

In [39]:
myarr = np.array([[10,76,15],[34,86,43],[85,63,42],[99,34,21]], dtype=np.float64)

In [40]:
myarr

array([[10., 76., 15.],
       [34., 86., 43.],
       [85., 63., 42.],
       [99., 34., 21.]])

In [41]:
myarr.dtype

dtype('float64')

In [44]:
myarr.astype(np.float32)

array([[10., 76., 15.],
       [34., 86., 43.],
       [85., 63., 42.],
       [99., 34., 21.]], dtype=float32)

In [45]:
myarr = np.array([[10,76,15],[34,86,43],[85,63,42],[99,34,21]])


In [46]:
myarr.shape

(4, 3)

In [57]:
myarr.reshape((6,2))

array([[10, 76],
       [15, 34],
       [86, 43],
       [85, 63],
       [42, 99],
       [34, 21]])