In [2]:
import numpy as np

In [3]:
arr = np.array([12,42,54])
arr.dtype

dtype('int64')

In [5]:
arr.astype(np.float64)

array([12., 42., 54.])

In [7]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_large

array([1000000, 2000000, 3000000])

In [9]:
arr_small = arr_large.astype(np.int32)
arr_small

array([1000000, 2000000, 3000000], dtype=int32)

In [10]:
arr_large.nbytes

24

In [11]:
arr_small.nbytes

12

In [13]:
arr = np.array(["aple","king","how"])
arr

array(['aple', 'king', 'how'], dtype='<U4')

In [14]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]
