In [1]:
import numpy as np

In [4]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(np.sum(arr,axis=0))
np.sum(arr,axis=1)

[12 15 18]


array([ 6, 15, 24])

In [14]:
arr[0][1]

np.int64(2)

In [15]:
arr[0,1]

np.int64(2)

In [18]:
arr[0:2,1:4]

array([[2, 3],
       [5, 6]])

In [19]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [20]:
arr3D[0,1,2]

np.int64(6)

In [36]:
arr3D[:,0,1:]

array([[2, 3],
       [8, 9]])

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])