In [1]:
import numpy as np

In [40]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
flat = arr.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
flat[0]
flat[5]
flat[3:10]
flat[::2]

array([1, 3, 5, 7, 9])

In [35]:
b = flat[3:6]
b[0] = 999
print(b)

[999   5   6]


In [36]:
flat

array([  1,   2,   3, 999,   5,   6,   7,   8,   9])

In [43]:
b = flat[3:6].copy()
b[1] = 999
print(b)

[999 999   6]


In [44]:
flat

array([  1,   2,   3, 999,   5,   6,   7,   8,   9])

In [48]:
arr = np.array([12,46,64,12,56,124])

In [51]:
arr[[1,3,0]]

array([46, 12, 12])

In [52]:
arr[arr <50]

array([12, 46, 12])

In [62]:
qw = np.array([[10,22,33],[4.4,5.5,6.6],[77,88,99]])
qw.shape

(3, 3)

In [75]:
myarr = qw.astype(int)
print(myarr)
myarr = myarr.flatten()

[[10 22 33]
 [ 4  5  6]
 [77 88 99]]


In [82]:
myarr[myarr %2 == 0]

array([10, 22,  4,  6, 88])

In [84]:
myarr.resize(9)

In [85]:
myarr

array([10, 22, 33,  4,  5,  6, 77, 88, 99])

In [86]:
myarr[myarr > 50]

array([77, 88, 99])